pipeline {
    agent any

    stages {
        stage('Unit Test backend') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'mkdir -p .gocache .gomodcache'
                    sh 'GOCACHE=$(pwd)/.gocache GOMODCACHE=$(pwd)/.gomodcache go test -v ./... 2>&1 | go-junit-report > report.xml'

                // Generate coverage report
                    sh 'GOCACHE=$(pwd)/.gocache GOMODCACHE=$(pwd)/.gomodcache go test -coverprofile=coverage.out -covermode=atomic ./...'
                    sh 'go tool cover -html=coverage.out -o coverage.html'
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/report.xml'
                    
                }
            }
        }

        stage('Unit Test frontend') {
            agent{
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                    npm ci
                    npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
            }
        }

        stage('launch application') {
            agent{
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }
            steps {
                withEnv(['DOCKER_HOST=unix:///var/run/docker.sock']) {
                    sh 'docker compose up --build -d'
                }
            }
        }
    }
}