pipeline {
    agent any

    stages {
        stage('Unit Test backend') {
            agent{
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'mkdir -p .gocache .gomodcache'
                    sh 'GOCACHE=$(pwd)/.gocache GOMODCACHE=$(pwd)/.gomodcache go test -v ./...'
                }
            }
        }
    }
}